module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "app-primary": "var(--app-primary)",
        "app-secondary": "var(--app-secondary)",
        black: "var(--black)",
        "black-2": "var(--black-2)",
        "black-3": "var(--black-3)",
        blue: "var(--blue)",
        "color-white": "var(--color-white)",
        "gray-00": "var(--gray-00)",
        "gray-1": "var(--gray-1)",
        "gray-100": "var(--gray-100)",
        "gray-2": "var(--gray-2)",
        "gray-3": "var(--gray-3)",
        "gray-4": "var(--gray-4)",
        gry: "var(--gry)",
        "gry-600": "var(--gry-600)",
        liner: "var(--liner)",
        red: "var(--red)",
        white: "var(--white)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "24": "var(--24-font-family)",
        "48": "var(--48-font-family)",
        "18-up": "var(--18-up-font-family)",
        h1: "var(--h1-font-family)",
        h2: "var(--h2-font-family)",
        h3: "var(--h3-font-family)",
        h4: "var(--h4-font-family)",
        h5: "var(--h5-font-family)",
        h6: "var(--h6-font-family)",
        "large-text-bold": "var(--large-text-bold-font-family)",
        "medium-text-bold": "var(--medium-text-bold-font-family)",
        "medium-text-regular": "var(--medium-text-regular-font-family)",
        "normal-text-bold": "var(--normal-text-bold-font-family)",
        overview: "var(--overview-font-family)",
        "small-text-bold": "var(--small-text-bold-font-family)",
        "small-text-regular": "var(--small-text-regular-font-family)",
        "sub-1": "var(--sub-1-font-family)",
        "text-normal-bold": "var(--text-normal-bold-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: {
        card: "var(--card)",
        drop: "var(--drop)",
        "drop-shadow-400": "var(--drop-shadow-400)",
        "drop-shadow-600": "var(--drop-shadow-600)",
        dropdown: "var(--dropdown)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
